version: "3.3"
services:
  spark-master:
    hostname: sparkmaster
    build: .
    image: cluster-apache-spark:3.3.2
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
      - ./apps:/opt/spark-apps
      - ./data:/opt/spark-data
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_WORKLOAD=master
  spark-worker-a:
    build: .
    image: cluster-apache-spark:3.3.2
    ports:
      - "9091:8080"
      - "7000:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=8
      - SPARK_WORKER_MEMORY=8G
      - SPARK_DRIVER_MEMORY=8G
      - SPARK_EXECUTOR_MEMORY=8G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-a
    volumes:
      - ./apps:/opt/spark-apps
      - ./data:/opt/spark-data
 # spark-worker-b:
   # build: .
    #image: cluster-apache-spark:3.3.2
    #ports:
     # - "9092:8080"
     # - "7001:7000"
    #depends_on:
     # - spark-master
    #environment:
     # - SPARK_MASTER=spark://spark-master:7077
     # - SPARK_WORKER_CORES=4
     # - SPARK_WORKER_MEMORY=3G
     # - SPARK_DRIVER_MEMORY=3G
     # - SPARK_EXECUTOR_MEMORY=3G
     # - SPARK_WORKLOAD=worker
     # - SPARK_LOCAL_IP=spark-worker-b
   # volumes:
     # - ./apps:/opt/spark-apps
      #- ./data:/opt/spark-data
